@DientesLimpios.API_HostAddress = https://localhost:7049/api/consultorios

GET {{DientesLimpios.API_HostAddress}}/019BC8EA-AEE2-7376-9E73-FBE84221D37C
Accept: application/json

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
{
  "nombre":"Consultorio 101"
}